import { Layout } from '@/components/layout/Layout'
import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

const About: NextPage = () => {
    return (
        <>
            <Head>
                <title>About page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className='mx-6 text-3xl text-slate-600'>
                    About page
                </div>
            </Layout>
        </>
    )
}
export default About 