import { GetStaticProps, NextPage } from 'next'
import { GetServerSideProps } from "next"
import Head from "next/head"
import HomePage from '@/components/screens/home/Home'
import type { TCharacter } from "@/types/CharacterType"
import { CharactersService } from "@/services/character.service"


const Home: NextPage<{ characters: TCharacter[] }> = ({ characters }) => {
  return <>
    <Head>
      <title>Home page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HomePage characters={characters} />
  </>
}


export const getStaticProps: GetStaticProps<{ characters: TCharacter[] }> = async () => {

  const characters = await CharactersService.GetSixRandomCharacters()

  return {
    props: { characters },
    revalidate: 600
  }
}



export default Home